name: version tag

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: blob:none

      - name: Calculate semantic version
        id: version
        uses: paulhatch/semantic-version@v6.0.2
        with:
          tag_prefix: "v"
          major_pattern: "/!:|BREAKING CHANGE:/"
          minor_pattern: "/feat(\\(.+\\))?:/"
          version_format: "${major}.${minor}.${patch}"
          search_commit_body: true
          enable_prerelease_mode: false

      - name: Create version tag
        if: steps.version.outputs.is_tagged != 'true'
        env:
          VERSION_TAG: ${{ steps.version.outputs.version_tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "$VERSION_TAG"
          git push origin "$VERSION_TAG"
